ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "firstName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "lastName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "jerseyNumber" TEXT;
