ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "sandlotRules" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "disabledPositions" JSONB;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "extraOutfielder" BOOLEAN NOT NULL DEFAULT false;
